version: 0.2 
env:
  variables:
    ECR_URI: 310714472748.dkr.ecr.us-east-1.amazonaws.com
    REGION: us-east-1
    IMAGE_NAME: ros-melodic-example
    RELEASE: latest
phases: 
  pre_build:
    commands:
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URI 
  build: 
    commands: 
      - docker build -f example.dockerfile -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:$RELEASE $ECR_URI/$IMAGE_NAME:$RELEASE
  post_build: 
    commands: 
      - docker push $ECR_URI/$IMAGE_NAME:$RELEASE
    